### ISSUE TITLE
Checksum fails in the past few days

### ISSUE THREAD

**Issue by KuraiAndras** [xoofx/UnityNuGet#147]
We have been getting random checksum fails from the azure hosted registry. Did we break something or is this a problem with the registry?
```
15:24:07 [DBG]     org.nuget.system.memory: Tarball download failed after [1] attempts. Downloaded [63296] bytes, expected [63296]:
15:24:07 [DBG]       shasum check failed for C:\ProgramData\Unity\cache\npm\unitynuget-registry.azurewebsites.net\.tmp-12896-rlrZKQCZKY4E\tarball\package.tgz
15:24:07 [DBG]       Expected: 494002bc9ae57ac74a4db8513da4782de700e1a0
15:24:07 [DBG]       Actual:   d1d514578675e35023a03f2f38644b93bd8d1d72
```

I always happens with the `org.nuget.system.memory` package and we can't reliably reproduce this.
This happens on 2 VM build agents that we host on prem, and they have been working fine up until yesterday.
We did not install any new packages, and everything works fine on developer machines

**Comment by xoofx** [comment]
I would think that when we change the content of the packages (e.g when we support new features like roslyn analyzers, or native dlls) it will change the checksum, and we don't have a way to resolve this client side because this is not expected (in an ideal package ecosystem, you cannot change published packages). With UnityNuGet, you need to remove all the local Unity caches to make sure that it doesn't have an old version of the package.

**Comment by KuraiAndras** [comment]
Thanks, I will try clearing the caches tomorrow morning and post if it helped

**Comment by KuraiAndras** [comment]
Yes, this seems to have fixed the problem, thanks for the quick reply
