### ISSUE TITLE
Server down, no enough space on disk

### ISSUE THREAD

**Issue by bdovaz** [xoofx/UnityNuGet#175]
@xoofx with the new release everything has stopped working due to lack of space :(

![image](https://user-images.githubusercontent.com/950602/219609941-080599f4-3459-436c-8011-c38b0f329367.png)

**Comment by xoofx** [comment]
Yeah, it happened already in the past. I think I was able to workaround it by removing NuGet cache. I will try to fix it later today.

**Comment by bdovaz** [comment]
Thanks!

**Comment by bdovaz** [comment]
@xoofx friendly reminder 🤗

Because I don't have access and I can't fix it myself, otherwise you know I would have helped you.

**Comment by xoofx** [comment]
Oh, sorry, completely forgot. 🐢 

I'm trying to reboot things after removing the `.nuget` folder. The culprit seems to be that the `.nuget` folder becomes gigantic like taking almost 45GB on its own (much more than the npm packages we generate)

I'm wondering maybe if a task that would clean this folder from time to time (e.g every day, on the next refresh) would be enough to avoid it blowing up. 

If you have the time to implement such feature, we could try 🙂

**Comment by xoofx** [comment]
Just checking the logs... at 3.7% completion, the `.nuget` folder is eating 15GB, seems that awsdk alone is taking a good chunk of this (because it has a huge number of versions)
For sure, having these NuGet packages duplicated around is really not great specially if in the end we don't need to update the npm packages (I forgot the details why it requires to redownload the package entirely but ideally, we should not if we have already the package around)

**Comment by xoofx** [comment]
Yeah, rereading the code, it can't scale as we are re-downloading all the NuGet packages at every single refresh. That was working initially for a small amount of packages but it should be done differently now (e.g skip packages already transformed)

**Comment by xoofx** [comment]
Ok, the server can't no longer handle all the packages, so the the update process will have to be changed to not download the package if it is already created/up-to-date.

**Comment by bdovaz** [comment]
@xoofx I'm analyzing the problem but without knowing well the NuGet.Protocol APIs it's hard to know how to change the code because....

In this line it downloads the package to a file in the filesystem:

https://github.com/xoofx/UnityNuGet/blob/3c66ad750a85ab118f3d233808241c77baa1d2fd/src/UnityNuGet/RegistryCache.cs#L234

It would be the first thing to check to see if it is possible only to download it in memory (and dispose later) and read it as Stream, that would solve the problem since this project does not need the original NuGet package for anything once it processes it and converts it to UPM format.

The dependencies of that downloadResult are here:

https://github.com/xoofx/UnityNuGet/blob/3c66ad750a85ab118f3d233808241c77baa1d2fd/src/UnityNuGet/RegistryCache.cs#L241

https://github.com/xoofx/UnityNuGet/blob/3c66ad750a85ab118f3d233808241c77baa1d2fd/src/UnityNuGet/RegistryCache.cs#L400

In both cases only the `PackageReader` property is used.

**Comment by xoofx** [comment]
Yeah, that should be mainly about not performing `GetDownloadResourceResultAsync`... but maybe also to avoid the recomputing of the registry entirely. E.g store the NpmPackage description on the disk and reload them quickly at restart and only update them when e.g a new package is updated.

**Comment by bdovaz** [comment]
@xoofx but well the main problem is to analyze how possible it is to avoid that `GetDownloadResourceResultAsync` to disk and see if it is possible as I said only to do it in memory.

The second thing you mention is important for performance so that the initial boot or each refresh is much faster but without that "it would work just as well".

**Comment by bdovaz** [comment]
I'm checking the class that has that method and the problem is that we have to pass a string with the path where to store the cache. I don't know if there is another way to use it other than recreating that class completely to try to avoid storing it on disk?

https://github.com/NuGet/NuGet.Client/blob/45751f85596108166f5428f8fe9f05fafd52b880/src/NuGet.Core/NuGet.PackageManagement/PackageDownloader.cs

**Comment by xoofx** [comment]
I don't think it is a problem to have this on the disk. We could perfectly remove the package `.nuget\$package` folder each time we probe for it.

The main issue is to avoid entirely `GetDownloadResourceResultAsync` but instead to make a diff with a deserialized version of NpmPackage. Because NuGet package is immutable, we know that a package already processed hasn't changed, so we don't need to re-process it.

**Comment by bdovaz** [comment]
@xoofx PR created, see what you think.

As you can see I have solved:
- The fact that the NuGet cache takes up a lot of disk. Now every time a package is converted, it clears the NuGet one which is no longer needed.
- I have optimized the startup/refresh process by calling the `GetDownloadResourceResultAsync` method in the strictly necessary situations.

Let's see if you see the changes well and we can leave this resolved and deployed today so that the server is available as soon as possible.

**Comment by bdovaz** [comment]
> but instead to make a diff with a deserialized version of NpmPackage. Because a NuGet package is immutable, we know that a package already processed hasn't changed, so we don't need to re-process it.

I have evaluated what you have told me but seeing that with the changes I have applied I think I have solved the problem quite well, I have not seen it necessary to spend more time on the PR.

We can think about it and if you see it necessary I can do it in a later PR with more calm. The important thing now is to have the server operational again as soon as possible.
