### ISSUE TITLE
CI takes 50 minutes because it checks every version of every package

### ISSUE THREAD

**Issue by Alexejhero** [xoofx/UnityNuGet#197]
It should only check the new packages that were added since the last tag push

**Comment by bdovaz** [comment]
@Alexejhero are you willing to create a PR?

**Comment by Alexejhero** [comment]
nuh uh

**Comment by Alexejhero** [comment]
https://fvsch.com/stale-bots

**Comment by bdovaz** [comment]
@Alexejhero currently I am the only one contributing to anything other than simply adding a new package.

This issue makes sense and I already posted if you were willing to help and I see you didn't respond nor has anyone else responded.

With the current architecture at least I can't think of a way to solve this problem, so unless you contribute something this issue is going to end up closed sooner or later.
