### ISSUE TITLE
Customize the Unity package scope per imported package

### ISSUE THREAD

**Issue by bucurb** [xoofx/UnityNuGet#216]
It would be nice to be able to add only "com." to packages starting with "Microsoft..." for instance. As well, for packages such as CliWrap, it would be nice to be able to scope to "com.tyrrrz."

**Comment by bdovaz** [comment]
If we allow that use case and start creating PRs of packages with `UnityScope` of type:

```json
"My.Package": {
},
"My.Package2": {
    "UnityScope": "my.scope2"
},
"My.Package3": {
    "UnityScope": "my.scope2"
},
```

It becomes a mess because there are packages that would be installed with "org.nuget.my.package" and others with "my.scope.my.package2" or "my.scope2.my.package3".

I don't see it right that it can be changed per package, but globally and this is already possible:

https://github.com/xoofx/UnityNuGet/blob/c9f5a1acbcbc2461a8bd07d103cd8071d2494fc2/examples/docker/docker-compose.yml#L7
