### ISSUE TITLE
Package registry down?

### ISSUE THREAD

**Issue by Nezz** [xoofx/UnityNuGet#57]
We are receiving 503 errors when trying to resolve or list packages in the registry:
```
[Package Manager Window] Request [GET https://unitynuget-registry.azurewebsites.net/-/v1/search?text=org.nuget&from=0&size=250] failed with status code [503]

[Package Manager Window] Cannot perform upm operation: Request [GET https://unitynuget-registry.azurewebsites.net/-/v1/search?text=org.nuget&from=0&size=250] failed with status code [503] [NotFound].
```
```
 An error occurred while resolving packages:
   Package org.nuget.system.collections.immutable@5.0.0 has invalid dependencies or related test packages:
     org.nuget.system.memory (dependency): Request [GET https://unitynuget-registry.azurewebsites.net/org.nuget.system.memory] failed with status code [503]
   Package org.nuget.system.memory@4.5.4 has invalid dependencies or related test packages:
     org.nuget.system.buffers (dependency): Request [GET https://unitynuget-registry.azurewebsites.net/org.nuget.system.buffers] failed with status code [503]
     org.nuget.system.numerics.vectors (dependency): Request [GET https://unitynuget-registry.azurewebsites.net/org.nuget.system.numerics.vectors] failed with status code [503]
     org.nuget.system.runtime.compilerservices.unsafe (dependency): Request [GET https://unitynuget-registry.azurewebsites.net/org.nuget.system.runtime.compilerservices.unsafe] failed with status code [503]
```
Is it having some trouble?

**Comment by xoofx** [comment]
Unfortunately, the latest release broke it, investigating...

**Comment by xoofx** [comment]
The registry should be back online. The problem was that the initialization was blocking the server to really start and after a period (seems like 10min) Azure decide to shutdown the server.
So I have removed the blocking initializer, let the server accessible returning a JSON error not initialized (with the % completion) and allow the updater to run immediately (as it was already running in the past immediately after the init)
Unfortunately, you need to remove the cache for UPM packages in your local app Unity Cache folder (on Windows: `%localappdata%\Unity\cache\npm\unitynuget-registry.azurewebsites.net`) in order to properly update to the newer server.
